import os

CONFIG_FILE = 'config.json'
CLOUDWATCH_NAMESPACE = 'MemCache Metrics 2'
AWS_ACCESS_KEY_ID = "AKIARYPZNG6KRLLMQZ3X"
AWS_SECRET_ACCESS_KEY = "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"
#AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
#AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
REGION_NAME = os.environ.get('REGION_NAME', 'us-east-1')
NOTIFICATION_ENDPOINT_URL = 'http://127.0.0.1:5000/nodeupdate'
